### PR TITLE
Adding StatefulDoFnRunner to DirectRunner demonstrates unstability

### PR DESCRIPTION
**Pull request by je-ik**

### CODE REVIEW

**Comment by rezarokni** [comment]
Added a new test that uses 2 keys, in this PullRequest that test fails most of the time. So its not a specific issue with the larger cache or the cache GC. As the small test only uses 2 values.

**Comment by je-ik** [comment]
@rezarokni Can you please send link to the commit with the 2 key test?

**Comment by rezarokni** [comment]
Its pushed into this PR. 
https://github.com/rezarokni/beam/commit/c471563392c1efbab3a101e8000747bc22b04f1e

Super interesting, I just tried adding a bunch more keys, so on the first OnTimer all state for all keys is available. However for the next OnTimer call, only the state for some of the keys remains, the other is wiped. One odd item is that datakey value is also cleared. That should only be done via the GC. But checking in my code again, was a while since I looked at this bit.

**Comment by je-ik** [comment]
Hm, what you describe is exactly what should have been fixed by the PR apache#9190 (cherry-picked in this branch).

**Comment by rezarokni** [comment]
It appears to be working for the first key but not the rest. Although that could just be test artifact. Will try and find time to look through the 9190 either later this week or next.

**Comment by je-ik** [comment]
Hm, I think I know the cause. If you apply this patch
```
diff --git a/runners/direct-java/src/main/java/org/apache/beam/runners/direct/WatermarkManager.java b/runners/direct-java/src/main/java/org/apache/beam/runners/direct/WatermarkManager.java
index d8da1125da..f518aff4a9 100644
--- a/runners/direct-java/src/main/java/org/apache/beam/runners/direct/WatermarkManager.java
+++ b/runners/direct-java/src/main/java/org/apache/beam/runners/direct/WatermarkManager.java
@@ -329,6 +329,12 @@ public class WatermarkManager<ExecutableT, CollectionT> {
 
     @VisibleForTesting
     synchronized void updateTimers(TimerUpdate update) {
+      if (!Iterables.isEmpty(update.getCompletedTimers())
+          || !Iterables.isEmpty(update.getSetTimers())
+          || !Iterables.isEmpty(update.getDeletedTimers())) {
+        System.err.println(
+            " *** timer update " + update + " at input watermark " + currentWatermark.get());
+      }
       NavigableSet<TimerData> keyTimers =
           objectTimers.computeIfAbsent(update.key, k -> new TreeSet<>());
       Table<StateNamespace, String, TimerData> existingTimersForKey =
```
You will notice something like this in case of failed test:
```
 *** timer update TimerUpdate(key=org.apache.beam.runners.local.StructuralKey$CoderStructuralKey@212804, setTimers=[TimerData{timerId=processTimer, namespace=Window([1999-12-25T00:00:00.000Z..2000-01-24T00:00:00.000Z)), timestamp=2000-01-01T00:15:00.500Z, domain=EVENT_TIME}], completedTimers=[TimerData{timerId=processTimer, namespace=Window([1999-12-25T00:00:00.000Z..2000-01-24T00:00:00.000Z)), timestamp=2000-01-01T00:15:00.000Z, domain=EVENT_TIME}], deletedTimers=[]) at input watermark 294247-01-10T04:00:54.775Z
 *** timer update TimerUpdate(key=org.apache.beam.runners.local.StructuralKey$CoderStructuralKey@212804, setTimers=[TimerData{timerId=__StatefulParDoGcTimerId, namespace=Window([1999-12-25T00:00:00.000Z..2000-01-24T00:00:00.000Z)), timestamp=2000-01-24T00:00:00.000Z, domain=EVENT_TIME}], completedTimers=[TimerData{timerId=processTimer, namespace=Window([1999-12-25T00:00:00.000Z..2000-01-24T00:00:00.000Z)), timestamp=2000-01-01T00:15:00.500Z, domain=EVENT_TIME}], deletedTimers=[]) at input watermark 294247-01-10T04:00:54.775Z
```
The timer `processTimer` was set up when the watermark was actually already at MAX_TIMESTAMP and the bundle already contained fired GC timer.

There is currently no simple workaround in user code. It can be solved in runner code, because runner knows the actual input watermark and can act accordingly. This way I solved it in apache/#8774
The only solution for user code, would be to create a hook in DirectRunner that will push back an already fired timer if some element being processed in current bundle causes a timer being setup for any time between current input and output watermark. That is pretty large refactoring I'm afraid.

**Comment by je-ik** [comment]
Kenn have found the issue. This comment describes why it breaks for multiple keys: https://github.com/apache/beam/pull/9190/files#r313977188
Will fix that in the PR apache#9190 and then backport it here.

**Comment by je-ik** [comment]
@rezarokni So, the test failures seem to be unrelated to a bug Kenn found, but I managed to get the tests passing (all but `BiTemporalCacheTest`) by changing `Create` to `TestStream` transform. That is strange and suggests, that there is still something wrong in DirectRunner that causes timers to behave incorrectly when using `Create` transform on input. Will look into that. Don't know what is happening with the `BiTemporalCacheTest`, though. The commit that fixed the other tests was https://github.com/rezarokni/beam/pull/2/commits/d31115592a5777a533627369b8a1dad02b818a80.

**Comment by je-ik** [comment]
Hm, commit https://github.com/apache/beam/pull/9190/commits/aa94c344c03449b6b9680b83aee9a53c422d297e should have revealed the failure in DirectRunner validatesRunner, but it seems to pass the test. Although the conditions should be somewhat similar to what happens in BiTemporalJoin. Mistery continues.

**Comment by rezarokni** [comment]
FYI raised https://issues.apache.org/jira/browse/BEAM-8090.
Kenn has some thoughts on this that he will explore.

**Comment by rezarokni** [comment]
Have started to validate these tests with different runners, so far its not reproducing outside of the DirectRunner. But will need to do more tests. 

FYI for the commands, for others that may want to try things out: 
To test in different runners:

Flink:
./gradlew :runners:flink:1.8:validatesRunnerStreaming --tests "**<yourTest>"

Dataflow: 
You will need to set Command Line params for your Dataflow project, but same as above

**Pull request closed without merging**
